apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  namespace: platform-keycloak
data:
  lcn-realm.json: |
    {
      "realm": "lcn",
      "enabled": true,
      "displayName": "LCN Lab Realm",
      "registrationAllowed": false,
      "resetPasswordAllowed": true,
      "rememberMe": true,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "sslRequired": "external",
      "users": [
        {
          "username": "developer",
          "enabled": true,
          "emailVerified": true,
          "firstName": "Developer",
          "lastName": "User",
          "email": "developer@lcn.local",
          "credentials": [
            {
              "type": "password",
              "value": "developer",
              "temporary": true
            }
          ],
          "realmRoles": ["default-roles-lcn"]
        }
      ]
    }
