---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-credentials
  namespace: platform-keycloak
spec:
  encryptedData:
    admin-password: AgBujomgmKR/e6ju9ZZ11mxMewNioM9i5ClNyuUxLDYGvlfjyMIk4ZOO94YQqM+uo0rjquk5qNS6jP+fnW6xgMSH3/Vk0yALYC1CVIgtf9hEqUmPiR89VBSG3Xi1ws0NgAGhQ/tOFzYskN1x81GH2GdJAcv7iuoAwAPjJYhMf28kbInJmB92UhJ5r3hxjgAl3NQCZH1wBPz8FD65AkhHIaEOkgEQLnsK3ZCZ0m1fyzGBEkfi9/kCW+eYiR9U3weV+tINj/jX95IJhm+LizhbGwmSKk0Aev4Cs6wRemJMhB8Y4pHxYRtQhhsRDWvY17Y3TQ/OvX5gxv8/eazOdGAzKWrYyBlYsNH81gxH3QSSFOBJZ3Zj76vKJexHmMPJW93zT5xV5Xn95ZPpUbkrsEx0Quafi28ldeD76vo7/LuvIkSBZRIiV5K+Frs32MspflR2T1Ow3auXQmEUbgu8sqMuSOQLPTq6QCZ36ZYejfiTXpR0JCI9Fcd30ZHzA5a9P8wbiv5U4fMCegP4+tlS0M7+9JPcSom3Yq46LxSrXC/I9sdTOS8gSYbXZgOPJ4PIcZjK9WvtsEl8/cFkvXWiEOohBpOoe7BgkdMD1xI16b5pnIHvE2c8M901URPd3H/8zYcbioXnAq6qvclxN1tg80Bei5sf/dgMTA8YNJXcR6lppmikObvVgfvVIZMUJMS4vUTu7vJbOIrsgUvRYM1HP30FCYZppjTFjyVRyfY=
  template:
    metadata:
      name: keycloak-admin-credentials
      namespace: platform-keycloak
