---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-app-credentials
  namespace: platform-mongodb
spec:
  encryptedData:
    password: AgAlQ+yWT7oMBubN1rHwyEGiDy1uhDQ8ZY/zAfoG8+ztJdz0HQiuCYXX2uGmP3nMD9+6qqsqHi6KrTc6BzTSXUxDEvisrqibxxPBi7y/SLfL55nN+mqOFUyV4azMSFgO6+YXd1fI1Ad+aLU+cxoYkI9lWL2DUavRwpk+LBZwsS6/8JAsUK2CY28jYWyFVRaTw3nQsTVj/uKeVOO1m0QY261J1kJEojUSYgBld2konkeYeNiSYO9AuRE9x0gYqG6cD4524nsqRpBZsRZRPvgUxLUB7ztxXpjhz9oy8jiapiJuDiMMLCUnezrMymEvMGjVO6tCnykU9rrId25LhzvgI4iO3DmI11V/PGX+VV2Qhm7E9lxlKpdp0GSa9retke+cYw8TqXko5driy74Q74PjaIscbkG4oWCAdEiTuZ+zqaJ/KNrAB/nP+FhwxYEQ6vSDj9texHLFAfLj4oo6yYOsTJW5QTyLZ2lRqXicWdlCD40pLgEzM4lhFxZzK/qN+y3LNE3MVoFkFS0JDb6ooyjke3sR+KGo0H28VmyML3kU9X/dMylBvCLChtI8n2z0ABQ+4SfdvJ9wMxfAdeLag3NolgOK2HIQvgJxFDexp+w4BM1ZCy6N01+A+gbFmk+0ABWbL3/ABkXww54FfPPgTFocnVHX9Mp4Vi26gsVVN2M6H93ZKmlVo+bXOlkUR0wEDhjeo5W2ro1Rmc/AyKluVJZFawZ/XGinXEwZaaI=
  template:
    metadata:
      name: mongodb-app-credentials
      namespace: platform-mongodb
