---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-app-credentials
  namespace: platform-mongodb
spec:
  encryptedData:
    mongodb-passwords: AgCYaf+h+L7cWvqtzSPEdE8rVLb7YklD3s2z+ncv04/SqZMDvZC2EKPETD7W0np2iBkYOsD2twLQ53h+M0aFrILOcqlTeFNOdSuKEBuvNbur5AksANnm6symUjj6R5UlS3M2PttlsXXG5oslfQdg6lR4MECIb3cHtlYkxu1lvGISCLtUX0OYqvWX3kRs0tl0SN6u2Bskhy1Fop7joLVrJLsMQW3/ni6PXOezCm6hCvgxAaVhhY8Ixn233LzyDNo2lHDYeNOWu3yEIxPObdCxvose35xqsF5NZcclj2tWUFhR1is4QeA6sfdrIFTYFFOjvx5dmx8XwQXLRsE0e1TxxLpI82MV5CSO2Yi5h16QqgK/UZnX1HjYvcu9U93kUFUx3cYyFwy7QMPmqTi4AfG9Io6VIuLFxrs2EwF1s7UOBUZPTDlohXMNbYBYwt1wlSSryBd6krAV2DxRxYr/IL2jXIw8/uzJU6bPdPgY+xu9uscfAjvIWB6VNb2DEnJYcdsEAOJsx6vhfeOuNU8zOceX+Huc+h3XuCeELCk11nEVOepOpGJeiHQSTlDOIXkrMMky5cTB+fk2wr7+fV//GoHKXHwg2rP8Rxxdml+8nj2wvAgjJtvhCGniaiYcQSTcDfIKAhYgx3ELNETVYou3jEvmn1hWp4aPlp5JfjOC2jQfDxyNLErRKrNys8nhxRKpEUvS1T0fsBwBsRDw/aNrXSfMnwGBOH6ipX+7Uck=
  template:
    metadata:
      name: mongodb-app-credentials
      namespace: platform-mongodb
